// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nabvfsbrrasdsaibnyby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hYnZmc2JycmFzZHNhaWJueWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjQ4ODUsImV4cCI6MjA2NzY0MDg4NX0.P6JCo1DFc1sSkvRY5BITC961t8Is4GqG_Scu9q8_EgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});