name: Build and Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Build main project
        run: npm run build

      - name: Add extra static files to dist
        run: |
          mkdir -p dist
          echo "✔ Másolás a dist mappába..."
          find . -maxdepth 1 -name '*.html' -exec cp -v {} dist/ \;
          [ -d blog ] && mkdir -p dist/blog && cp -a blog/. dist/blog/ || echo "⚠️ blog mappa nem található"
          [ -d assets ] && mkdir -p dist/assets && cp -a assets/. dist/assets/ || echo "⚠️ assets mappa nem található"
          [ -d images ] && mkdir -p dist/images && cp -a images/. dist/images/ || echo "⚠️ images mappa nem található"
          [ -d bootstrap ] && mkdir -p dist/bootstrap && cp -a bootstrap/. dist/bootstrap/ || echo "⚠️ bootstrap mappa nem található"
          mkdir -p dist/public && cp -a public/. dist/public/ || echo "⚠️ public mappa nem másolható"
          mkdir -p dist/src && cp -a sr
