name: Build and Deploy to FTP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy blog folder to dist/
        run: |
          mkdir -p dist/blog
          cp -r blog/* dist/blog || echo "No blog folder found"

      - name: Copy Bootstrap JS files to dist/assets/js/
        run: |
          mkdir -p dist/assets/js
          cp public/assets/bootstrap/js/*.js dist/assets/js/

      - name: Copy custom script to dist/assets/js
        run: |
          mkdir -p dist/assets/js
          cp public/assets/js/script.min.js dist/assets/js/

      - name: Copy admin.html to dist/
        run: cp admin.html dist/


      - name: Deploy to FTP (includes /dist + blog + js)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.tibby.hu
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          protocol: ftp
          security: loose
          passive: true
          local-dir: ./dist/
          delete: false
          include-dotfiles: true
          dry-run: false

